### ISSUE TITLE
"mvn clean install" geht nicht im starter-project

### ISSUE THREAD

**Issue by pubkey** [WI13C/Jgui-creator#18]
>  Failed to execute goal on project pruefungsaufgabe: Could not resolve dependencies for project pruefungsaufgabe:pruefungsaufgabe:jar:0.0.1-SNAPSHOT: Failed to collect dependencies at de.dhbw.wi13c.jguicreator:framework:jar:0.0.1-SNAPSHOT: Failed to read artifact descriptor for de.dhbw.wi13c.jguicreator:framework:jar:0.0.1-SNAPSHOT: Could not find artifact de.dhbw.wi13c.jguicreator:parent:pom:${project.version} in central (https://repo.maven.apache.org/maven2) -> [Help 1]

**Comment by freeerunner** [comment]
Du musst vorher das framework mit "mvn clean install" bauen, zudem stater nicht als maven projekt bauen, sondern einfach als java application starten. Macen wird hier nur bemutzt um das framework rein zu hängen.

**Comment by danielsun174** [comment]
Folgendes hab ich gemacht:

1. im ordner code "mvn clean install" ausgeführt -> BUILD SUCESS
2. Via eclipse die Showcase.java gestartet -> Funktioniert wie gewollt
3. Mit eclipse als jar-file sowie runnable-jar exportiert. Der Export an sich geht. Die generierte jar ist jedoch nicht startbar. Zudem gibts beim export compile-fehler. Habe alle möglichen Export-Optionen durchgetestet.

**Comment by danielsun174** [comment]
Hier der Error:

´´´
faggot@Macbook ~/Desktop $ java -jar Untitled.jar 
Person [vorname=Hans, nachname=Maier, anzahlKinder=3, Geburtsdatum=Sat Apr 24 00:00:00 CEST 3880, adresse=Adresse [strasse=Hauptstra�e, Hausnummer=30], kontaktDaten=[Kontakt [typ=privat, telefon=0160123456, email=ferdi@prov.de], Kontakt [typ=business, telefon=0173555666, email=ferdi@busy.com]], einkommensZusammensetzung={Zinsen=15000, Miete=20000, Gehalt=35000}, einkommensEntwicklung={2013=34123.12, 2012=33131.64, 2011=29263.12, 2010=27323.54}]
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.IllegalArgumentException: input == null!
	at javax.imageio.ImageIO.read(ImageIO.java:1348)
	at de.dhbw.wi13c.jguicreator.elemente.TextFieldMitLabel.<init>(TextFieldMitLabel.java:81)
	at de.dhbw.wi13c.jguicreator.impl.SwingVisitor.visit(SwingVisitor.java:53)
	at de.dhbw.wi13c.jguicreator.data.uielements.TextfieldData.accept(TextfieldData.java:25)
	at de.dhbw.wi13c.jguicreator.impl.RootGui.init(RootGui.java:81)
	at de.dhbw.wi13c.jguicreator.impl.RootGui.<init>(RootGui.java:56)
	at de.dhbw.wi13c.jguicreator.impl.GuiCreator.createView(GuiCreator.java:20)
	at de.dhbw.vs.jprakt.exam.testclasses.Showcase.main(Showcase.java:51)
	... 5 more
´´´

**Comment by freeerunner** [comment]
Passt doch soweit, wird auch gestartet, siehst an den ersten consolen ausgaben, nur dann crashed es, warum kann ich dir nicht sagen... Nur soviel, dass der starter nie dazu konzipiert war als standalone zu arbeiten, ist der von ferdi und ich nehme an er wird da im code noch was ändern wenn er es testet ...

**Comment by freeerunner** [comment]
Ihm fehlt ein bild zum laden... ImageIO wirft nullpointer ... Ressource nicht im jar

**Comment by danielsun174** [comment]
Erich hats gefixed -> Closed
